name: build
env:
  version: '4.1.6'

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prepare template
        run: |
          mkdir -p td-libwebsockets-dev_${{env.version}}
          cp -rv DEBIAN.template td-libwebsockets-dev_${{env.version}}/DEBIAN
          sed -i "s/%VERSION%/${{env.version}}/g" td-libwebsockets-dev_${{env.version}}/DEBIAN/*
      - name: Download lib
        run: |
          mkdir -p td-libwebsockets-dev_${{env.version}}/usr/local/src
          cd td-libwebsockets-dev_${{env.version}}/usr/local/src
          curl -L -o libwebsockets-${{env.version}}.tar.gz https://github.com/warmcat/libwebsockets/archive/v${{env.version}}.tar.gz
          tar zvxf libwebsockets-${{env.version}}.tar.gz
          rm libwebsockets-${{env.version}}.tar.gz
      - name: Build .deb
        run: |
          dpkg-deb --build td-libwebsockets-dev_${{env.version}}
          mkdir -p dist
          mv td-libwebsockets-dev_${{env.version}}.deb dist
      - name: Try install
        working-directory: dist
        run: |
          sudo dpkg -i td-libwebsockets-dev_${{env.version}}.deb
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          REPOSITORY_NAME: tada-team/ppa
          TARGET_FOLDER: td-libwebsockets-dev-dist
          FOLDER: dist
          SSH: true
          BRANCH: main
