---
name: build
env:
  # version: '4.1.6'  # undefined symbol: lws_validity_confirmed
  version: '3.2.2'

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Download source code
        run: |
          wget 'https://github.com/warmcat/libwebsockets/archive/refs/tags/v3.2.2.tar.gz' \
            --output-document libwebsockets_3.2.2.orig.tar.gz
      - name: Verify source archive
        run: |
          sha256sum --check ./hash.txt
      - name: Extract source
        run: |
          tar --extract --file ./libwebsockets_3.2.2.orig.tar.gz
      - name: Create build directories
        run: |
          cp -r ./libwebsockets-3.2.2 ./build_amd64
          cp -r ./libwebsockets-3.2.2 ./build_arm64
      - name: Copy debian directory
        run: |
          cp -r ./debian ./build_amd64
          cp -r ./debian ./build_arm64
      - name: Add ARM64 architecture
        run: |
          sudo dpkg --add-architecture arm64
      - name: Update sources.list
        run: |
          cat ./bionic-sources.txt | sudo tee /etc/apt/sources.list
      - name: Update package list
        run: |
          sudo apt update
      - name: Install AMD64 build dependencies
        run: |
          sudo apt install binutils-aarch64-linux-gnu build-essential \
            crossbuild-essential-arm64 devscripts debhelper cmake \
            libcap-dev libev-dev libssl-dev libuv1-dev openssl zlib1g-dev
      - name: Build AMD64  # Must be built before ARM64 as libev-dev:amd64 conflict libev-dev:arm64
        run: |
          cd ./build_amd64
          debuild --unsigned-source --unsigned-buildinfo --unsigned-changes
      - name: Install ARM64 dependencies
        run: |
          sudo apt install libcap-dev:arm64 libev-dev:arm64 \
            libssl-dev:arm64 libuv1-dev:arm64 zlib1g-dev:arm64
      - name: Build ARM64
        run: |
          cd ./build_arm64
          debuild --host-arch arm64 \
            --unsigned-source --unsigned-buildinfo --unsigned-changes
      - name: Copy built packages
        run: |
          mkdir dist
          mv ./td-libwebsockets*.deb ./dist
      - name: Try install
        working-directory: dist
        run: |
          ls
          sudo apt install libev-dev  # Fix dependency
          sudo dpkg --install ./td-libwebsockets-dev_3.2.2-1_amd64.deb \
            ./td-libwebsockets_3.2.2-1_amd64.deb
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          REPOSITORY_NAME: tada-team/ppa
          TARGET_FOLDER: td-libwebsockets-dev-dist
          FOLDER: dist
          SSH: true
          BRANCH: main
